### ISSUE TITLE
[READ THIS FIRST] Format for reporting Bugs.

### ISSUE THREAD

**Issue by Marfjeh** [Marfjeh/MarfBOT_Issues#1]
For reporting bugs you need to have this format:

1. What happend

2. What command and arguments (if any)

3. What did you expect? (optinal)

**Comment by megaxlr** [comment]
I suggest looking into templating instead of writing your own issue.

also add some labels for any moderators to add.

GitHub has a nice integration for issue and pull-request templates [here](https://github.com/blog/2111-issue-and-pull-request-templates)
